spring.application.name=webapp

server.port=8080

spring.datasource.url=jdbc:postgresql://seg1-webapp-pgsql.ca7aeo0qw3zv.us-east-1.rds.amazonaws.com:5432/webapp
spring.datasource.username=rootuser
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework=DEBUG